server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Parking_mg
    username: postgres
    password: 106513545


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update